# Generated by Django 4.2.4 on 2023-08-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='rbooks/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tiles',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
