# Generated by Django 4.2.4 on 2023-09-06 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_dialogue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialogue',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='rbooks',
            options={'ordering': ['id'], 'verbose_name': 'Books to read', 'verbose_name_plural': 'Books to read'},
        ),
        migrations.AlterModelOptions(
            name='tiles',
            options={'ordering': ['id'], 'verbose_name': 'Course books', 'verbose_name_plural': 'Course books'},
        ),
        migrations.AddField(
            model_name='dialogue',
            name='words',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
